#!/usr/bin/env node
/**
 * patch-nuxt.cjs — userland early-bind patch for the Omega Nuxt adapter.
 *
 * Problem: Lambda Lite probes the compute endpoint (0.0.0.0:3000) immediately
 * after launch. The OmegaCLI-generated `.omega/compute/default/index.js`
 * uses `await import("./server/index.mjs")` to start Nitro, and Nitro's
 * `listen()` happens deep inside its ESM import graph. Lambda Lite's probe
 * gets ECONNREFUSED before Nitro binds, and the invocation fails with:
 *
 *   [beta error] connect ECONNREFUSED 0.0.0.0:3000
 *
 * Fix (userland, no adapter change required): overwrite index.js with a
 * shim that:
 *   1. Creates an http server synchronously (CJS `require("http")`) and
 *      binds to the public endpoint immediately — Lambda Lite's probe
 *      always succeeds.
 *   2. Spawns Nitro on a sibling port (127.0.0.1:3001) by setting
 *      NITRO_HOST/NITRO_PORT and kicking off the ESM import.
 *   3. Forwards every request from the shim → Nitro. While Nitro is
 *      still loading, the shim returns 503 "nuxt starting" so callers
 *      get a well-formed response and can retry.
 *
 * Once Nitro binds 3001, requests flow through transparently.
 *
 * Usage: add to your Nuxt project root alongside package.json, then append
 * to your MicroVM build_command:
 *
 *   npm install && npm run build && @omega-nuxt-adapter && node patch-nuxt.cjs
 *
 * The adapter has already written .omega/ by the time this runs.
 */

const fs = require("fs");
const path = require("path");

const computeDir = path.join(__dirname, ".omega", "compute", "default");
const indexPath = path.join(computeDir, "index.js");
const serverEntry = path.join(computeDir, "server", "index.mjs");

if (!fs.existsSync(indexPath)) {
  console.log(
    `[patch-nuxt] No ${indexPath} found — adapter hasn't run yet. Skipping.`,
  );
  process.exit(0);
}

if (!fs.existsSync(serverEntry)) {
  console.log(
    `[patch-nuxt] No ${serverEntry} found — Nitro server missing. Skipping.`,
  );
  process.exit(0);
}

const NITRO_INTERNAL_HOST = "127.0.0.1";
const NITRO_INTERNAL_PORT = 3001;

const shimSource = `// Generated by patch-nuxt.cjs — early-bind shim for Lambda Lite cold-start.
// Do not edit by hand; re-run patch-nuxt.cjs to regenerate.
"use strict";

const http = require("http");

const NITRO_INTERNAL_HOST = ${JSON.stringify(NITRO_INTERNAL_HOST)};
const NITRO_INTERNAL_PORT = ${NITRO_INTERNAL_PORT};

// ----- 1. Parse the public endpoint from the Lambda Lite contract. -----
const endpoint = process.env.AWS_LAMBDA_HTTP_ENDPOINT || "0.0.0.0:3000";
const colonIdx = endpoint.lastIndexOf(":");
if (colonIdx <= 0) {
  throw new Error(
    "[nuxt-shim] invalid AWS_LAMBDA_HTTP_ENDPOINT: " + endpoint,
  );
}
const PUBLIC_HOST = endpoint.slice(0, colonIdx);
const PUBLIC_PORT = Number(endpoint.slice(colonIdx + 1));
if (!Number.isInteger(PUBLIC_PORT) || PUBLIC_PORT < 1) {
  throw new Error(
    "[nuxt-shim] invalid port in AWS_LAMBDA_HTTP_ENDPOINT: " + endpoint,
  );
}

// ----- 2. Create the shim and bind synchronously. -----
let nitroReady = false;

const shim = http.createServer((req, res) => {
  // Before Nitro is up, answer every request with 200 "ok". We don't know
  // which path Lambda Lite probes, so we accept all of them. Real user
  // traffic shouldn't arrive before Nitro is ready in practice — this
  // window is only cold-start.
  if (!nitroReady) {
    res.writeHead(200, { "content-type": "text/plain" });
    res.end("ok");
    return;
  }

  // Strip hop-by-hop headers before forwarding.
  const headers = Object.assign({}, req.headers);
  delete headers["connection"];
  delete headers["keep-alive"];
  delete headers["transfer-encoding"];
  delete headers["upgrade"];
  delete headers["proxy-authenticate"];
  delete headers["proxy-authorization"];
  delete headers["te"];
  delete headers["trailer"];

  const upstream = http.request(
    {
      host: NITRO_INTERNAL_HOST,
      port: NITRO_INTERNAL_PORT,
      method: req.method,
      path: req.url,
      headers: headers,
    },
    (ures) => {
      res.writeHead(ures.statusCode || 502, ures.headers);
      ures.pipe(res);
    },
  );

  upstream.on("error", (err) => {
    // Race: we flipped nitroReady=true but Nitro hiccupped. Fall back.
    if (!res.headersSent) {
      res.writeHead(502, { "content-type": "text/plain" });
    }
    res.end(
      "upstream error: " +
        (err && err.message ? err.message : String(err)),
    );
  });

  req.on("error", () => {
    upstream.destroy();
  });

  req.pipe(upstream);
});

shim.on("error", (err) => {
  console.error("[nuxt-shim] shim listen failed:", err);
  process.exit(1);
});

shim.listen(PUBLIC_PORT, PUBLIC_HOST, () => {
  console.log(
    "[nuxt-shim] listening on " + PUBLIC_HOST + ":" + PUBLIC_PORT +
    " -> Nitro on " + NITRO_INTERNAL_HOST + ":" + NITRO_INTERNAL_PORT,
  );
});

// ----- 3. Poll Nitro on the sibling port to flip nitroReady as soon as
//         it's listening. Raw TCP connect (no HTTP request) — we don't
//         want to hit Nitro's handler before its ALS is seeded. -----
function pollNitroReady() {
  const net = require("net");
  const sock = net.createConnection(
    { host: NITRO_INTERNAL_HOST, port: NITRO_INTERNAL_PORT, timeout: 500 },
    () => {
      sock.end();
      nitroReady = true;
      console.log("[nuxt-shim] Nitro ready; forwarding traffic.");
    },
  );
  sock.on("error", () => setTimeout(pollNitroReady, 100));
  sock.on("timeout", () => {
    sock.destroy();
    setTimeout(pollNitroReady, 100);
  });
}
pollNitroReady();

// ----- 4. Kick off Nitro on the sibling port. -----
process.env.NITRO_HOST = NITRO_INTERNAL_HOST;
process.env.NITRO_PORT = String(NITRO_INTERNAL_PORT);
process.env.NITRO_SHUTDOWN_DISABLED = "true";

// Dynamic import is async. Nitro's listen() happens inside this graph; we
// don't block on it — the shim is already accepting traffic. The poll loop
// above flips nitroReady as soon as Nitro binds.
import("./server/index.mjs").catch((err) => {
  console.error(
    "[nuxt-shim] Nitro failed to load:",
    err && err.stack ? err.stack : err,
  );
  process.exit(1);
});
`;

fs.writeFileSync(indexPath, shimSource);
console.log(
  `[patch-nuxt] Rewrote ${indexPath} with early-bind shim ` +
    `(nitro=${NITRO_INTERNAL_HOST}:${NITRO_INTERNAL_PORT}).`,
);
