#!/usr/bin/env node
/**
 * patch-nuxt-v2.cjs — userland Option-2 (eager-import reorder) patch for
 * the Omega Nuxt adapter.
 *
 * Problem: same as patch-nuxt.cjs — Lambda Lite probes 0.0.0.0:3000 before
 * Nitro binds, ECONNREFUSED, fail.
 *
 * Option 2 fix: rewrite .omega/compute/default/index.js so that Nitro's
 * ESM import is the FIRST thing that runs. No pre-work, no extra log
 * lines, no env plumbing before the import. The hope is that Nitro
 * (which binds ~32ms after listen() in measured tests) beats Lambda
 * Lite's probe deadline without a shim.
 *
 * If this works, the adapter-side fix is a 5-line reorder in
 * @amzn/omega-runtime-proxy/src/proxy.ts. If it doesn't, Option 1
 * (patch-nuxt.cjs) is the right path.
 *
 * Usage: drop into Nuxt project root, append to build_command:
 *
 *   npm install && npm run build && @omega-nuxt-adapter && node patch-nuxt-v2.cjs
 */

const fs = require("fs");
const path = require("path");

const computeDir = path.join(__dirname, ".omega", "compute", "default");
const indexPath = path.join(computeDir, "index.js");
const serverEntry = path.join(computeDir, "server", "index.mjs");

if (!fs.existsSync(indexPath)) {
  console.log(
    `[patch-nuxt-v2] No ${indexPath} found — adapter hasn't run yet. Skipping.`,
  );
  process.exit(0);
}

if (!fs.existsSync(serverEntry)) {
  console.log(
    `[patch-nuxt-v2] No ${serverEntry} found — Nitro server missing. Skipping.`,
  );
  process.exit(0);
}

const eagerSource = `// Generated by patch-nuxt-v2.cjs — eager Nitro import for Lambda Lite cold-start.
// Do not edit by hand; re-run patch-nuxt-v2.cjs to regenerate.
//
// Compared to the default adapter output, this skips startProxy's pre-work
// (env plumbing, signal handlers, waitForReady polling) so Nitro's import
// graph — which calls listen() inside — starts as early as possible.
// Nitro reads NITRO_HOST/NITRO_PORT itself (defaulting to 0.0.0.0:3000),
// which matches the AWS_LAMBDA_HTTP_ENDPOINT Lambda Lite expects.

// Parse the endpoint Lambda Lite is going to probe and hand it to Nitro
// via its native env vars. Keep this cheap — no imports, no I/O.
const endpoint = process.env.AWS_LAMBDA_HTTP_ENDPOINT || "0.0.0.0:3000";
const colonIdx = endpoint.lastIndexOf(":");
if (colonIdx > 0) {
  process.env.NITRO_HOST = endpoint.slice(0, colonIdx);
  process.env.NITRO_PORT = endpoint.slice(colonIdx + 1);
}
process.env.NITRO_SHUTDOWN_DISABLED = "true";

// Kick off Nitro's import graph immediately. Nitro will bind the port
// (listen()) as part of its top-level initialization. Any error
// propagates up; Lambda Lite kills the process.
await import("./server/index.mjs");
`;

fs.writeFileSync(indexPath, eagerSource);
console.log(
  `[patch-nuxt-v2] Rewrote ${indexPath} with eager Nitro import (Option 2).`,
);
